# Generated by Django 3.2.8 on 2021-10-20 12:48

import aphrodite.models.base.mixins
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('label', models.CharField(help_text='The label for this menu item.', max_length=128)),
                ('index', models.IntegerField(help_text='The index (order) that this menu item should appear in the menu.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('heading', models.CharField(help_text='The heading for this menu section, to appear above its sub-items.', max_length=128)),
                ('index', models.IntegerField(help_text='The index (order) that this section should appear in the submenu.', unique=True)),
                ('menu', models.ForeignKey(help_text='The menu item this section should appear below.', on_delete=django.db.models.deletion.CASCADE, to='aphrodite.menuitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(help_text='The title of this page.', max_length=128)),
                ('subtitle', models.TextField(blank=True, help_text='The subtitle to appear below the title.')),
                ('slug', models.SlugField(blank=True, help_text='How this article will appear in URLs (leave blank for auto).', max_length=128, unique=True)),
                ('summary', models.TextField(blank=True, help_text='A short summary of the article for the homepage.')),
                ('content', ckeditor.fields.RichTextField(help_text='The content of this page.')),
                ('banner_image', models.ImageField(blank=True, help_text='The image that should appear at the very top of the page. It should be wide, and high quality.', null=True, upload_to='page/banner/')),
                ('index_page', models.BooleanField(default=False, help_text='Should this page be the index page of the website?')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, aphrodite.models.base.mixins.AutoSlugMixin),
        ),
        migrations.CreateModel(
            name='MenuSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('label', models.CharField(help_text='The label for this link.', max_length=128)),
                ('index', models.IntegerField(help_text='The index (order) that this link should appear in the section.', unique=True)),
                ('page', models.ForeignKey(help_text='The page this link should navigate to.', on_delete=django.db.models.deletion.CASCADE, to='aphrodite.page')),
                ('section', models.ForeignKey(help_text='The menu section this link should belong to.', on_delete=django.db.models.deletion.CASCADE, to='aphrodite.menusection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
