# Generated by Django 3.2.8 on 2021-10-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aphrodite', '0002_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusection',
            name='menu',
            field=models.ForeignKey(help_text='The menu item this section should appear below.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='aphrodite.menuitem'),
        ),
        migrations.AlterField(
            model_name='menusectionitem',
            name='section',
            field=models.ForeignKey(help_text='The menu section this link should belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aphrodite.menusection'),
        ),
    ]
