# Generated by Django 3.2.8 on 2021-10-20 15:25

import aphrodite.models.base.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aphrodite', '0003_auto_20211020_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(help_text='The name of this category.', max_length=128)),
                ('slug', models.SlugField(blank=True, help_text='How this article will appear in URLs (leave blank for auto).', max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=(models.Model, aphrodite.models.base.mixins.AutoSlugMixin),
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(default=1, help_text="The category that this page belongs to. Will appear in the page's URL.", on_delete=django.db.models.deletion.CASCADE, to='aphrodite.category'),
            preserve_default=False,
        ),
    ]
