# Generated by Django 3.2.8 on 2021-10-20 15:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aphrodite', '0004_auto_20211020_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='The content of this page.'),
        ),
    ]
