# Generated by Django 3.2.8 on 2021-10-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aphrodite', '0005_alter_page_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='menusection',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='menusectionitem',
            options={'ordering': ['index']},
        ),
    ]
