# Generated by Django 3.2.8 on 2021-10-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aphrodite', '0006_auto_20211020_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='index',
            field=models.IntegerField(help_text='The index (order) that this menu item should appear in the menu.', unique=True),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='index',
            field=models.IntegerField(help_text='The index (order) that this section should appear in the submenu.'),
        ),
        migrations.AlterField(
            model_name='menusectionitem',
            name='index',
            field=models.IntegerField(help_text='The index (order) that this link should appear in the section.'),
        ),
        migrations.AlterUniqueTogether(
            name='menusection',
            unique_together={('menu', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='menusectionitem',
            unique_together={('section', 'index')},
        ),
    ]
